

DECLARE @OLD NVARCHAR(50) = 'MOLD'
DECLARE @NEW NVARCHAR(50) = 'IMM'

UPDATE dbo.MAY SET MS_MAY = REPLACE(MS_MAY,@OLD,@NEW)
SELECT C.name AS COLUMN_NAME, T.name AS TABLE_NAME INTO #T FROM sys.columns C JOIN sys.tables T ON T.object_id = C.object_id WHERE C.name Like '%MS_MAY%'

DECLARE @TB NVARCHAR(50) = ''
DECLARE @CN NVARCHAR(50) = ''
DECLARE @Sql NVARCHAR(MAX) = ''
WHILE (SELECT COUNT(*) FROM #T) > 0
BEGIN
	SET @TB = (SELECT TOP 1 TABLE_NAME FROM #T)
	SET @CN = (SELECT TOP 1 COLUMN_NAME FROM #T)

	SET @Sql = 'UPDATE dbo.' + @TB + ' SET  MS_MAY = REPLACE(MS_MAY,''' + @OLD + ''','''+ @NEW +''')'
	EXEC (@Sql)

	DELETE #T WHERE TABLE_NAME = @TB AND COLUMN_NAME = @CN
END

DROP TABLE #T


