--SELECT * FROM dbo.ActualHMI WHERE MS_MAY = 'IMM-01' AND CONVERT(DATE,Date) = '2022-04-07' AND ItemID = 47 ORDER BY Date

DECLARE @MS_MAY NVARCHAR(50) ='IMM-02';
DECLARE @Ngay DATETIME= GETDATE()

SELECT N'chạy' AS ten, Date,MS_MAY,ItemID,CONVERT(NVARCHAR(50),ActualQuanity) AS SL,-1 AS TINHOEE FROM dbo.ActualHMI WHERE MS_MAY = @MS_MAY AND CONVERT(DATE,Date) = dbo.fnGetNgayTheoCa(@Ngay) 
UNION
SELECT 'ngung',TU_GIO,MS_MAY,' ',NGUYEN_NHAN,(SELECT OEE FROM dbo.NGUYEN_NHAN_DUNG_MAY A WHERE A.MS_NGUYEN_NHAN  = B.MS_NGUYEN_NHAN) AS TINHOEE from dbo.THOI_GIAN_DUNG_MAY B WHERE MS_MAY = @MS_MAY AND CONVERT(DATE,TU_GIO) = dbo.fnGetNgayTheoCa(@Ngay) 
ORDER BY Date




