--SELECT MIN(Date) AS MINCA, MS_MAY, ProID, ItemID, OperatorID, ID_CA, ActualQuanity FROM dbo.ActualHMI WHERE  ID_CA =2 AND CONVERT(TIME,DATE) > '22:00:00' AND CONVERT(TIME,DATE)< '22:05:00' 
--GROUP BY MS_MAY, ProID, ItemID, OperatorID, ID_CA, ActualQuanity 
--SELECT * FROM dbo.CA


DECLARE @DenGio TIME = '14:00:00'
DECLARE @QuaDem INT = 0
DECLARE @Ca INT = 1
DECLARE @CaDen INT = 2
--INSERT INTO	dbo.ActualHMI(Date, MS_MAY, ProID, ItemID, OperatorID, ID_CA, ActualQuanity)
--SELECT T1.Date, T1.MS_MAY, T1.ProID, T1.ItemID, T1.OperatorID, T1.ID_CA, T1.SLTUCUOICA FROM 
----SELECT T1.Date, T1.MS_MAY, T1.ProID, T1.ItemID, T1.OperatorID, T1.ID_CA, T1.SLTUCUOICA FROM 
--(

IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'#TMP') AND type in (N'U'))
BEGIN
	DROP TABLE #TMP
END

SELECT 
--T1.DATECUOICA, T1.DATEDAUCA, T1.SLCUOICA, T1.SLDAUCA, T1.MS_MAY, T1.ProID, T1.ItemID, T1.OperatorID, T1.SG2LAN, T1.SL2LAN, T1.SSP1GIAY, T1.DATECA, T1.DATETHEM
T1.DATETHEM AS Date ,T1.MS_MAY, T1.ProID, T1.ItemID, T1.OperatorID,@Ca AS ID_CA, T1.SLCUOICA + DATEDIFF(SECOND,T1.DATECUOICA,DATETHEM) *  T1.SSP1GIAY AS SLTUCUOICA
,NGAYDAUCA INTO	#TMP
FROM 
(
SELECT 
T1.DATECUOICA, T2.DATEDAUCA, T1.SLCUOICA, T2.SLDAUCA, T1.MS_MAY, T1.ProID, T1.ItemID, T1.OperatorID,
DATEDIFF(SECOND,T1.DATECUOICA, DATEADD(DAY,1, T2.DATEDAUCA)) AS SG2LAN, T2.SLDAUCA - T1.SLCUOICA AS SL2LAN,  (T2.SLDAUCA - T1.SLCUOICA) / DATEDIFF(SECOND,T1.DATECUOICA,DATEADD(DAY,@QuaDem, T2.DATEDAUCA)) AS SSP1GIAY,T2.NGAYDAUCA,
CONVERT(DATETIME, CONVERT(NVARCHAR(10),CONVERT(DATE,DATEADD(DAY,@QuaDem, T2.DATEDAUCA)),101) + ' ' + CONVERT(NVARCHAR(8),@DenGio)) AS DATECA
,DATEADD(SECOND,DATEDIFF(SECOND,T2.DATEDAUCA,CONVERT(DATETIME, CONVERT(NVARCHAR(10),DATEADD(DAY,@QuaDem, T2.DATEDAUCA),101) + ' ' + CONVERT(NVARCHAR(8),@DenGio))) + -1,T2.DATEDAUCA) AS DATETHEM
FROM (
SELECT T1.Date AS DATECUOICA, T1.MS_MAY, T1.ProID, T1.ItemID, T1.OperatorID, T1.ActualQuanity SLCUOICA , CONVERT(DATE,T1.Date) NGAYCUOICA FROM dbo.ActualHMI T1 INNER JOIN (
SELECT MAX(Date) DATECUOICA, MS_MAY, ProID, ItemID FROM dbo.ActualHMI WHERE ID_CA = @Ca AND CONVERT(TIME,CONVERT(VARCHAR, DATE, 8)) > DATEADD(MINUTE,-5,@DenGio) AND CONVERT(TIME,DATE)< @DenGio   GROUP BY MS_MAY, ProID, ItemID,  ID_CA  ) T2 ON T2.ItemID = T1.ItemID AND T2.MS_MAY = T1.MS_MAY AND T2.ProID = T1.ProID AND T2.DATECUOICA = T1.Date ) T1 INNER JOIN 
(SELECT T1.Date DATEDAUCA, T1.MS_MAY, T1.ProID, T1.ItemID, T1.OperatorID,  T1.ActualQuanity  SLDAUCA, CONVERT(DATE,T1.Date) NGAYDAUCA FROM dbo.ActualHMI T1 INNER JOIN (
SELECT MIN(Date) DATEDAUCA, MS_MAY, ProID, ItemID FROM dbo.ActualHMI WHERE ID_CA = @CaDen AND CONVERT(TIME,CONVERT(VARCHAR, DATE, 8)) > @DenGio AND CONVERT(TIME,DATE)< DATEADD(MINUTE,5,@DenGio)  GROUP BY MS_MAY, ProID, ItemID,  ID_CA  ) T2 ON T2.ItemID = T1.ItemID AND T2.MS_MAY = T1.MS_MAY AND T2.ProID = T1.ProID AND T2.DATEDAUCA = T1.Date ) T2 ON T2.ProID = T1.ProID AND T2.MS_MAY = T1.MS_MAY AND T2.ItemID = T1.ItemID    AND	 NGAYDAUCA  = NGAYCUOICA  

) T1 
ORDER BY T1.NGAYDAUCA, T1.MS_MAY, T1.ProID

SELECT * FROM #TMP WHERE NGAYDAUCA >= '03/01/2022'




SELECT A.Date,
       A.MS_MAY,
       A.ProID,
       A.ItemID,
       A.OperatorID,
       A.ID_CA,
       A.SLTUCUOICA,B.ActualQuantity FROM #TMP A
INNER JOIN dbo.ProductionRunDetails B ON B.ID_CA = A.ID_CA AND B.ItemID = A.ItemID AND B.MS_MAY = A.MS_MAY AND B.PrOID = A.ProID AND CONVERT(DATE,A.Date) = CONVERT(DATE,B.StartTime)