
--ALTER TABLE NGUYEN_NHAN_DUNG_MAY
--ADD  [AUTO_CYCLE] INT
ALTER proc [dbo].[spApiGETDowTime]
	@DownTimeTypeID BIGINT = 24
AS
BEGIN
		SELECT MS_NGUYEN_NHAN,TEN_NGUYEN_NHAN,CONVERT(INT,ISNULL(DefineLevel,0) * 60) AS DINH_MUC,ISNULL(AUTO_CYCLE,0) AS AUTO_CYCLE FROM dbo.NGUYEN_NHAN_DUNG_MAY WHERE DownTimeTypeID = @DownTimeTypeID
END




