//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commons
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThongBao
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThongBao()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commons.ThongBao", typeof(ThongBao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to msgDangSuDung.
        /// </summary>
        public static string msgDangSuDung
        {
            get
            {
                return ResourceManager.GetString("msgDangSuDung", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to msgKhongCoDuLieuXoa.
        /// </summary>
        public static string msgKhongCoDuLieuXoa
        {
            get
            {
                return ResourceManager.GetString("msgKhongCoDuLieuXoa", resourceCulture);
            }
        }




        /// <summary>
        ///   Looks up a localized string similar to msgXoa.
        /// </summary>
        public static string msgXoa
        {
            get
            {
                return ResourceManager.GetString("msgXoa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to msgXoaAll.
        /// </summary>
        public static string msgXoaAll
        {
            get
            {
                return ResourceManager.GetString("msgXoaAll", resourceCulture);
            }
        }
        public static string msgBanChuaChonDuLieu
        {
            get
            {
                return ResourceManager.GetString("msgBanChuaChonDuLieu", resourceCulture);
            }
        }
        public static string msgKhongCoDuLieuIn
        {
            get
            {
                return ResourceManager.GetString("msgKhongCoDuLieuIn", resourceCulture);
            }
        }
        public static string msgCapNhatThatBai
        {
            get
            {
                return ResourceManager.GetString("msgCapNhatThatBai", resourceCulture);
            }
        }

        public static string msgCapNhatThanhCong
        {
            get
            {
                return ResourceManager.GetString("msgCapNhatThanhCong", resourceCulture);
            }
        }

        public static string msgBanChuaChonDieuKienCanCapNhat
        {
            get
            {
                return ResourceManager.GetString("msgBanChuaChonDieuKienCanCapNhat", resourceCulture);
            }
        }

        public static string msgKhongHopLe
        {
            get
            {
                return ResourceManager.GetString("msgKhongHopLe", resourceCulture);
            }
        }
        public static string msgNgayBiTrungDuLieu

        {
            get
            {
                return ResourceManager.GetString("msgNgayBiTrungDuLieu", resourceCulture);
            }
        }
        public static string msgBanChuaNhapDuDuLieu
        {
            get
            {
                return ResourceManager.GetString("msgBanChuaNhapDuDuLieu", resourceCulture);
            }
        }
        public static string msgKhongCoDuLieuSua
        {
            get
            {
                return ResourceManager.GetString("msgKhongCoDuLieuSua", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string msgTBA
        {
            get
            {
                return ResourceManager.GetString("msgTBA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        public static string msgTBV
        {
            get
            {
                return ResourceManager.GetString("msgTBV", resourceCulture);
            }
        }
        public static string msgKhongDuocTrong
        {
            get
            {
                return ResourceManager.GetString("msgKhongDuocTrong", resourceCulture);
            }
        }

        public static string msgDaTonTai
        {
            get
            {
                return ResourceManager.GetString("msgDaTonTai", resourceCulture);
            }
        }
        public static string msgDuLieuDaPhatSinh
        {
            get
            {
                return ResourceManager.GetString("msgDuLieuDaPhatSinh", resourceCulture);
            }
        }
    }
}
