--INSERT INTO dbo.DON_VI_DO(TEN_DV_DO)
--SELECT TEN_DV_DO FROM CMMS_BARIA_TEST.dbo.TMP_DON_VI_DO


--UPDATE A
--SET A.TEN_TS_GSTT =B.TEN_TS_GSTT,
--A.TEN_TS_GSTT_ANH =B.TEN_TS_GSTT_ANH,
--A.TEN_TS_GSTT_HOA =B.TEN_TS_GSTT_HOA
--FROM dbo.THONG_SO_GSTT A
--INNER JOIN CMMS_BARIA_TEST.dbo.TMP_TS B ON A.MS_TS_GSTT =B.MS_TS_GSTT
-- WHERE ISNULL(B.TT,0) = 1

--UPDATE CMMS_BARIA_TEST.dbo.TMP_TS SET MS_DV_DO = NULL WHERE MS_DV_DO ='NULL'

--INSERT INTO dbo.THONG_SO_GSTT(MS_TS_GSTT,TEN_TS_GSTT,MS_DV_DO,LOAI_TS,GHI_CHU,MS_BP_GSTT,DUONG_DAN,MS_LOAI_CV,TEN_TS_GSTT_ANH,TEN_TS_GSTT_HOA)
--SELECT MS_TS_GSTT,TEN_TS_GSTT,MS_DV_DO,LOAI_TS,GHI_CHU,MS_BP_GSTT,DUONG_DAN,MS_LOAI_CV,TEN_TS_GSTT_ANH,TEN_TS_GSTT_HOA FROM CMMS_BARIA_TEST.dbo.TMP_TS WHERE ISNULL(TT,0) = 2

--INSERT INTO dbo.GIA_TRI_TS_GSTT(MS_TS_GSTT,TEN_GIA_TRI,DAT,GHI_CHU)
--SELECT MS_TS_GSTT,TEN_GIA_TRI,DAT,GHI_CHU FROM CMMS_BARIA_TEST.dbo.TMP_GTTS



--UPDATE A
--SET A.CHU_KY_DO =B.CHU_KY_DO,
--A.ACTIVE =B.ACTIVE,
--A.MS_DV_TG =B.MS_DV_TG
--FROM dbo.CAU_TRUC_THIET_BI_TS_GSTT A
--INNER JOIN CMMS_BARIA_TEST.dbo.TMP_CTTS B ON A.MS_MAY =B.MS_MAY AND B.MS_BO_PHAN = A.MS_BO_PHAN AND B.MS_TS_GSTT = A.MS_TS_GSTT AND A.MS_TT =B.MS_TT
--WHERE B.TT = 1


--UPDATE CMMS_BARIA_TEST.dbo.TMP_CTTS SET GIA_TRI_TREN = NULL WHERE GIA_TRI_TREN ='NULL'
--UPDATE CMMS_BARIA_TEST.dbo.TMP_CTTS SET GIA_TRI_DUOI = NULL WHERE GIA_TRI_DUOI ='NULL'

--INSERT INTO dbo.CAU_TRUC_THIET_BI_TS_GSTT(MS_MAY,MS_BO_PHAN,MS_TS_GSTT,MS_TT,TEN_GT,GIA_TRI_TREN,GIA_TRI_DUOI,CHU_KY_DO,MS_DV_TG,DAT,GHI_CHU,ACTIVE)
--SELECT MS_MAY,MS_BO_PHAN,MS_TS_GSTT,MS_TT,TEN_GT,GIA_TRI_TREN,GIA_TRI_DUOI,CHU_KY_DO,MS_DV_TG,DAT,GHI_CHU,ACTIVE FROM CMMS_BARIA_TEST.dbo.TMP_CTTS WHERE TT = 2

--INSERT INTO dbo.CAU_TRUC_THIET_BI_TS_GSTT(MS_MAY,MS_BO_PHAN,MS_TS_GSTT,MS_TT,TEN_GT,GIA_TRI_TREN,GIA_TRI_DUOI,CHU_KY_DO,MS_DV_TG,DAT,GHI_CHU,ACTIVE)
--SELECT MS_MAY,MS_BO_PHAN,MS_TS_GSTT,MS_TT,TEN_GT,GIA_TRI_TREN,GIA_TRI_DUOI,CHU_KY_DO,MS_DV_TG,DAT,GHI_CHU,ACTIVE FROM CMMS_BARIA_TEST.dbo.TMP_CTTS A WHERE  A.TT =1 AND a.ACTIVE = 1 AND NOT EXISTS(SELECT * FROM CAU_TRUC_THIET_BI_TS_GSTT B WHERE A.MS_MAY =B.MS_MAY AND B.MS_BO_PHAN = A.MS_BO_PHAN AND A.MS_TS_GSTT = B.MS_TS_GSTT AND  A.MS_TT =B.MS_TT) 


--INSERT INTO dbo.CAU_TRUC_THIET_BI(MS_MAY,MS_BO_PHAN,TEN_BO_PHAN,MS_PT,SO_LUONG,MS_BO_PHAN_CHA,GHI_CHU,RUN_TIME,MS_DVT_RT,HINH,CLASS_ID,STT,TEN_BO_PHAN_ANH,TEN_BO_PHAN_HOA)
--SELECT DISTINCT  A.MS_MAY,A.MS_BO_PHAN,A.TEN_BO_PHAN,NULL,1,A.MS_MAY,A.GHI_CHU,0,NULL,NULL,NULL,NULL,A.TEN_BO_PHAN,A.TEN_BO_PHAN FROM CMMS_BARIA_TEST.dbo.TMP_CTTS A
--WHERE NOT EXISTS(SELECT * FROM CAU_TRUC_THIET_BI B WHERE A.MS_MAY =B.MS_MAY AND B.MS_BO_PHAN = A.MS_BO_PHAN) 


