
CREATE TABLE [dbo].[ACTUAL_LABOR](
	[NGAY] [date] NOT NULL,
	[ACTUAL_LABOR] [float] NULL,
 CONSTRAINT [PK_ACTUAL_LABOR] PRIMARY KEY CLUSTERED 
(
	[NGAY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
