//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHA_XUONG
    {
        public NHA_XUONG()
        {
            this.NHA_XUONG1 = new HashSet<NHA_XUONG>();
        }
    
        public string MS_N_XUONG { get; set; }
        public string MS_CHA { get; set; }
        public string Ten_N_XUONG { get; set; }
        public string TEN_N_XUONG_A { get; set; }
        public string TEN_N_XUONG_H { get; set; }
        public string TRU_SO { get; set; }
        public string NGUOI_DAI_DIEN { get; set; }
        public string DIEN_THOAI { get; set; }
        public string MS_QG { get; set; }
        public string MS_DUONG { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<double> DIEN_TICH { get; set; }
        public Nullable<double> KHOANG_CACH { get; set; }
        public string GHI_CHU { get; set; }
        public string MS_DON_VI { get; set; }
        public byte[] HINH_ANH { get; set; }
    
        public virtual ICollection<NHA_XUONG> NHA_XUONG1 { get; set; }
        public virtual NHA_XUONG NHA_XUONG2 { get; set; }
    }
}
