//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class OEEDataContext : DbContext
    {
        public OEEDataContext()
            : base("name=OEEDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<USER> USERS { get; set; }
    
        public virtual ObjectResult<spGetData_Result> spGetData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetData_Result>("spGetData");
        }
    
        public virtual ObjectResult<spLCDFull_Result> spLCDFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLCDFull_Result>("spLCDFull");
        }
    }
}
