//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USERNAME { get; set; }
        public int GROUP_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string PASS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> MS_TO { get; set; }
        public string USER_MAIL { get; set; }
        public string MS_CONG_NHAN { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
