--SELECT dbo.fnGetThoiGianSua(8550)
ALTER function [dbo].[fnGetThoiGianSua]
(
	@IDNM BIGINT = 0
)
returns INT
AS 
BEGIN
    DECLARE @Resulst INT
	DECLARE @TU_GIO DATETIME 
	DECLARE @DEN_GIO DATETIME 
	
	SELECT TOP 1 @TU_GIO = TU_GIO,@DEN_GIO  =DEN_GIO FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID = @IDNM
	WHILE @IDNM IS NOT NULL
	BEGIN
		IF EXISTS(SELECT ID FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID_CHA = @IDNM )
		BEGIN
			SET @IDNM = (SELECT TOP 1 ID FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID_CHA = @IDNM)
		END
		ELSE 
		BEGIN
			SET @DEN_GIO = (SELECT TOP 1 DEN_GIO FROM dbo.THOI_GIAN_DUNG_MAY WHERE ID = @IDNM)
			SET @IDNM = NULL
		END
		END
	SET @Resulst = DATEDIFF(SECOND,@TU_GIO,@DEN_GIO)
RETURN ISNULL(@Resulst,0)
end
GO


